"""Change whatsapp field to string

Revision ID: 868fe8b6e3a7
Revises: 
Create Date: 2025-01-01 10:42:33.470598

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '868fe8b6e3a7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('complaint', schema=None) as batch_op:
        batch_op.alter_column('whatsapp',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=15),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('complaint', schema=None) as batch_op:
        batch_op.alter_column('whatsapp',
               existing_type=sa.String(length=15),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
